# Generated by Django 5.1.6 on 2025-02-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_unit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='долг перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='уровень в иерархии'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='products',
            field=models.ManyToManyField(blank=True, to='distribution.product', verbose_name='продукты'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_units', to='distribution.unit', verbose_name='поставщик'),
        ),
    ]
